### ISSUE TITLE
Documenting the Readme.md file

### ISSUE THREAD

**Issue by Xx-Ashutosh-xX** [Xx-Ashutosh-xX/SongBird#3]
Improve the current Readme.md file by adding more documentation.

If you are coming for Hacktoberfest PRs, do read the contribution rules on their site.

**Comment by rjayroso** [comment]
Hey, I would like to add more documentation to the README.md. Can you please assign this to me?

**Comment by Xx-Ashutosh-xX** [comment]
sure go ahead !
